### ISSUE TITLE
some questions about Calibration point cloud

### ISSUE THREAD

**Issue by DualMoonBird** [HaozheQi/P2B#13]
def getPCandBBfromPandas(self, box, calib):
        center = [box["x"], box["y"] - box["height"] / 2, box["z"]]
        size = [box["width"], box["length"], box["height"]]
        orientation = Quaternion(
            axis=[0, 1, 0], radians=box["rotation_y"]) * Quaternion(
                axis=[1, 0, 0], radians=np.pi / 2)
Using this function to convert point cloud coordinates to camera coordinates,the orientation use to move the cut point cloud to the origin of the camera coordinate system and turn it in a positive direction,I think orientation = Quaternion(axis=[0, 1, 0], radians=box["rotation_y"]) is ok,so why you choose to multiply Quaternion(axis=[1, 0, 0], radians=np.pi / 2)

**Comment by freshwk** [comment]
hello，i have the same question with you.Do you know why?

**Comment by ujaejoon** [comment]
@freshwk @DualMoonBird I have the same question. If you know the reason, can you share it with me?
