### ISSUE TITLE
training time and machines

### ISSUE THREAD

**Issue by WangZhouTao** [HaozheQi/P2B#4]
Hello, thanks for your good job. 
I noticed that you mentioned the running speed on a single NVIDIA 1080Ti GPU. Can you share the training time and what machines are used?

**Comment by HaozheQi** [comment]
Hi, @WangZhouTao, actually, we don't  count the training time strictly, it takes about 10 hours to converge the model with an Amax sever.

**Comment by WangZhouTao** [comment]
Hi, thanks for your reply.
In fact, I only have a 1080ti GPU. Can you tell me the type and number of GPUs in your Amax sever? In this way, I can assess whether I can retrain this framework.
looking forward to your reply.

**Comment by HaozheQi** [comment]
One GPU is OK for the training and you only need to change the settings in 'train_tracking.py' like that,
 `parser.add_argument('--ngpu', type=int, default=1, help='# GPUs')`
`os.environ["CUDA_VISIBLE_DEVICES"] = '0'`

**Comment by WangZhouTao** [comment]
Thanks for your reply.
