### ISSUE TITLE
some problem about the figure

### ISSUE THREAD

**Issue by WangZhouTao** [HaozheQi/P2B#6]
Hello, thanks for your good job.
The figure in the paper shows the effect of P2b very well(such as Fig. 7 9 10). What software do you use to visualize these point clouds and boxes? (mayavi? meshlab?)

**Comment by HaozheQi** [comment]
Hi, @WangZhouTao, I use mayavi for the visualization.

**Comment by WangZhouTao** [comment]
thanks for your reply~
